name: Docker .NET Runtime Dependencies CI

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix:
        dotnet: ['8.0','9.0']

    name: Build docker image for .NET ${{ matrix.dotnet }}
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and Push docker image for .NET ${{ matrix.dotnet }} to dockerhub
      uses: docker/build-push-action@v5
      env:
        DOCKERFILE_PATH: ./${{ matrix.dotnet }}/Dockerfile
        DOCKER_TAG: ${{ matrix.dotnet }}
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/dotnet-deps:${{ env.DOCKER_TAG }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dotnet-deps:${{ env.DOCKER_TAG }}-cache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dotnet-deps:${{ env.DOCKER_TAG }}-cache,mode=max

